# Site settings
name: Ashish Kumar Singh
title: Ashish Kumar Singh | Full-Stack developer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://bchiang7.github.io/
baseurl: ''
email: ashishsinghxr@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:ashishsinghxr@gmail.com
  - title: twitter
    url: https://x.com/ashishxsinghh
  - title: github
    url: https://github.com/ashishxsinghh

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
